#Set center server port
center.port=8181
center.password=4WlljLhTMU9Hs4m8
center.web.password=edzqerg24
center.server.name=AliceMS
# Database config
spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/alicems?autoReconnect=true&characterEncoding=UTF-8&rewriteBatchedStatements=true
spring.datasource.username=root
spring.datasource.password=root12311
# Data path
data.path=./WZ_JSON_TW
discord.webhook.url=https://www.google.com