# Center server host
game.center.ip=127.0.0.1
game.center.port=8181
game.center.password=4WlljLhTMU9Hs4m8
# Game server config
game.host=127.0.0.1
game.port=9001
game.serverId=0
game.worldId=0
game.channelId=1
game.event=server_tip,event_rps,event_bingo,event_marriage
game.slide=歪瑞谷(TMS) 歡迎您。 使用@help查看命令。
game.rate.lv_exp_rate={0:1,50:2,100:3,150:4,200:5,250:6,300:7}
game.rate.drop.boss=1
game.rate.drop.normal=1
game.rate.meso=1
# Mob's meso reward pickup limit
game.meso.pickup.max=0
# Buffer, skill and equipment bonus rate control
game.bonus.meso=true
game.bonus.drop=true
#
game.field.check.level=false
game.field.check.quest=false
game.field.burning.reset=true
game.field.burning.level.min=0
game.field.burning.level.max=10
# Data path
data.path=./WZ_JSON_TW
