#Center server host
login.center.ip=127.0.0.1
login.center.port=8181
login.center.password=4WlljLhTMU9Hs4m8
#Login server config
login.host=127.0.0.1
login.port=35856
#Decorated world info
login.background=default,2023annual
login.maintenance=false
login.world-flags={0:0,1:1}
login.world-messages={0:"楓之谷(TMS) 測試中。",1:"Welcome to springboot2."}
# burn event
login.burn=EventHyper2
# job select order
login.job.order=13
# Data path
data.path=./WZ_JSON_TW
